name: GitHub Repo Search

on:
  workflow_dispatch:
    inputs:
      keywords:
        description: 'Comma-separated keywords to search'
        required: true
        default: 'model context protocol server,mcp server,mcp framework,mcp sdk,mcp template,mcp utility,mcp gateway,mcp proxy,mcp client,mcp tutorial,mcp example,mcp database,mcp api,mcp storage,mcp ai,mcp chat,mcp search'
      min_stars:
        description: "Minimum number of stars a repo should have"
        required: false
        default: '10'
      min_forks:
        description: "Minimum number of forks a repo should have"
        required: false
        default: '5'
      output_file:
        description: 'Output json file path'
        required: false
        default: 'results/data.json'

jobs:
  search-github-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip' # Make sure you have requirements.txt file or pyproject.toml in your repo

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run GitHub repo search script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYWORDS_ENV: ${{ github.event.inputs.keywords }}
          MIN_STARS: ${{ github.event.inputs.min_stars }}
          MIN_FORKS: ${{ github.event.inputs.min_forks }}
          OUTPUT_FILE: ${{ github.event.inputs.output_file }}
        run: |
          python daily.py

      - name: Upload search results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: search-results
          path: ${{ github.event.inputs.output_file }}
